[default.extend-words]
Hashi = "Hashi" # as in HashiCorp
MAKIN = "MAKIN"
OT = "OT"
PN = "PN" # as in PNCounter
Welp = "Welp"
iterm = "iterm" # as in "iterm2.com"

[files]
extend-exclude = [
  "content/posts/crunch-str.md", # lots of intentionally-misspelled words
  "syntaxes/*",
  "public/*",
]
