[phases.setup]
nixPkgs = [
    '...',
    'zola',
    'nodePackages.html-minifier',
    'nodePackages.clean-css-cli',
    'pngcrush',
    'jpegoptim',
]

[phases.build]
cmds = [
    'zola build',
    'html-minifier --collapse-whitespace --decode-entities --remove-comments --remove-attribute-quotes --remove-redundant-attributes --remove-optional-tags --remove-script-type-attributes --remove-style-link-type-attributes --file-ext html --input-dir public --output-dir public',
    'cleancss -O 1 -o public/style.css public/style.css',
    'find public -type f -name "*.png" -exec pngcrush -rem alla -reduce -m 7 {} \;',
    'find public -type f -name "*.jpg" -exec jpegoptim --max=90 --strip-all --all-progressive --overwrite {} \;',
]
